# Generated by Django 2.0.4 on 2019-10-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('matricola', models.CharField(max_length=10, unique=True)),
                ('utenza', models.CharField(max_length=10, unique=True)),
                ('divisione', models.CharField(blank=True, max_length=50, null=True)),
                ('ruolo', models.CharField(choices=[('dir', 'dirigenza'), ('seg', 'segreteria')], default=('dir', 'dirigenza'), max_length=3)),
                ('attivo', models.BooleanField(default=True)),
                ('segretaria_associata', models.ManyToManyField(blank=True, related_name='_utente_segretaria_associata_+', to='anagrafica.Utente')),
            ],
            options={
                'verbose_name_plural': 'utenti',
                'ordering': ['cognome', '-attivo'],
            },
        ),
    ]
