# Generated by Django 2.0.4 on 2019-10-10 07:34

from django.db import migrations, models
import django.db.models.deletion
import interventi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivi', '0001_initial'),
        ('anagrafica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=40, null=True)),
                ('tipo_servizio', models.CharField(default='ENHANCED', max_length=20)),
                ('richiedente', models.CharField(default='ROSSELLA MACCHI', max_length=20)),
                ('data_richiesta', models.DateField(validators=[interventi.models.valida_data_richiesta])),
                ('data_chiusura', models.DateField(validators=[interventi.models.valida_data_chiusura])),
                ('tipo_ticket', models.CharField(choices=[('incident', 'incident'), ('IMAC', 'IMAC'), ('change', 'change'), ('move', 'move'), ('altro', 'altro')], max_length=30)),
                ('numero_ticket', models.CharField(blank=True, max_length=15, null=True)),
                ('area_intervento', models.CharField(choices=[('Applicativi', 'Applicativi'), ('Aree condivise', 'Aree condivise'), ('Backup/ripristino', 'Backup/ripristino'), ('Informazioni/procedure', 'Informazioni/procedure'), ('Messaging', 'Messaging'), ('Mobile', 'Mobile'), ('Move', 'Move'), ('PC HW', 'PC HW'), ('PC SW', 'PC SW'), ('Printing', 'Printing'), ('Sicurezza', 'Sicurezza'), ('TLC', 'TLC'), ('User Management', 'User Management'), ('Video/Audio comunicazione', 'Video/Audio comunicazione'), ('altro', 'altro')], max_length=30)),
                ('descrizione_richiesta', models.TextField(max_length=300)),
                ('soluzione_adottata', models.TextField(max_length=300)),
                ('stato_intervento', models.CharField(choices=[('chiuso', 'chiuso'), ('work in progress', 'work in progress'), ('pianificato', 'pianificato'), ('counter stop', 'counter stop'), ('cancellato', 'cancellato')], max_length=30)),
                ('tipo_ingaggio', models.CharField(choices=[('mail enhanced', 'mail enhanced'), ('mail Coppetta', 'mail Coppetta'), ('telefonata enhanced', 'telefonata enhanced'), ('telefonata Coppetta', 'telefonata Coppetta'), ('telefonata utente', 'telefonata utente')], max_length=30)),
                ('datetime_ingaggio', models.DateTimeField(blank=True, null=True, validators=[interventi.models.valida_datetime_ingaggio], verbose_name='data/ora ingaggio')),
                ('note', models.TextField(blank=True, max_length=300, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispositivi.Dispositivo', verbose_name='dispositivo')),
                ('fk_beneficiario', models.ForeignKey(limit_choices_to={'attivo': True}, on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Utente', verbose_name='beneficiario')),
            ],
            options={
                'verbose_name_plural': 'interventi',
            },
        ),
    ]
